### ISSUE TITLE
Error installing saltexe.vmware with master 3006 and debian 11

### ISSUE THREAD

**Issue by peterbaumert** [saltstack/salt-ext-modules-vmware#378]
I have 

```
local:
    Salt Version:
              Salt: 3006.1

    Python Version:
            Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
            relenv: 0.12.3
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist: debian 11 bullseye
            locale: utf-8
           machine: x86_64
           release: 5.10.0-21-amd64
            system: Linux
           version: Debian GNU/Linux 11 bullseye
```

and when trying to install according to the documentation i get the following error:

```
salt-call pip.install saltext.vmware
[ERROR   ] Command '/opt/saltstack/salt/salt-pip' failed with return code: 1
[ERROR   ] stdout: Collecting saltext.vmware
  Using cached saltext.vmware-23.4.4.0rc1-py2.py3-none-any.whl (396 kB)
Requirement already satisfied: salt>=3005 in /opt/saltstack/salt/lib/python3.10/site-packages (from saltext.vmware) (3006.1)
Collecting pyvmomi==7.0.3 (from saltext.vmware)
  Using cached pyvmomi-7.0.3.tar.gz (592 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting jinja2<=3.1.0 (from saltext.vmware)
  Using cached Jinja2-3.1.0-py3-none-any.whl (132 kB)
Requirement already satisfied: requests>=2.3.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (2.25.1)
Requirement already satisfied: six>=1.7.3 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from jinja2<=3.1.0->saltext.vmware) (2.1.2)
Requirement already satisfied: certifi==2022.12.7 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2022.12.7)
Requirement already satisfied: cffi==1.14.6 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.14.6)
Requirement already satisfied: chardet==3.0.4 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.0.4)
Requirement already satisfied: cheroot==8.5.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (8.5.2)
Requirement already satisfied: cherrypy==18.6.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (18.6.1)
Requirement already satisfied: contextvars==2.4 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.4)
Requirement already satisfied: cryptography==39.0.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (39.0.2)
Requirement already satisfied: distro==1.5.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.5.0)
Requirement already satisfied: idna==2.8 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.8)
Requirement already satisfied: immutables==0.15 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (0.15)
Requirement already satisfied: importlib-metadata==6.0.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (6.0.0)
Requirement already satisfied: jaraco.classes==3.2.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.2.1)
Requirement already satisfied: jaraco.collections==3.4.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.4.0)
Requirement already satisfied: jaraco.functools==2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.0)
Requirement already satisfied: jaraco.text==3.5.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.5.1)
INFO: pip is looking at multiple versions of salt to determine which version is compatible with other requirements. This could take a while.
Collecting salt>=3005 (from saltext.vmware)
  Using cached salt-3006.0.tar.gz (20.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
[ERROR   ] stderr:   error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      Fatal Python error: init_import_site: Failed to import the site module
      Python runtime state: initialized
      Traceback (most recent call last):
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 617, in <module>
          main()
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 610, in main
          execsitecustomize()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/relenv/runtime.py", line 744, in wrapper
          import sitecustomize
        File "/tmp/pip-build-env-wsulpl8c/site/sitecustomize.py", line 23, in <module>
          site.addsitedir(path)
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 216, in addsitedir
          sitedir, sitedircase = makepath(sitedir)
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 97, in makepath
          dir = os.path.join(*paths)
        File "/opt/saltstack/salt/lib/python3.10/posixpath.py", line 76, in join
          a = os.fspath(a)
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[ERROR   ] retcode: 1
local:
    ----------
    pid:
        2497380
    retcode:
        1
    stderr:
          error: subprocess-exited-with-error

          × Getting requirements to build wheel did not run successfully.
          │ exit code: 1
          ╰─> [20 lines of output]
              Error in sitecustomize; set PYTHONVERBOSE for traceback:
              TypeError: expected str, bytes or os.PathLike object, not NoneType
              Fatal Python error: init_import_site: Failed to import the site module
              Python runtime state: initialized
              Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site.py", line 617, in <module>
                  main()
                File "/opt/saltstack/salt/lib/python3.10/site.py", line 610, in main
                  execsitecustomize()
                File "/opt/saltstack/salt/lib/python3.10/site-packages/relenv/runtime.py", line 744, in wrapper
                  import sitecustomize
                File "/tmp/pip-build-env-wsulpl8c/site/sitecustomize.py", line 23, in <module>
                  site.addsitedir(path)
                File "/opt/saltstack/salt/lib/python3.10/site.py", line 216, in addsitedir
                  sitedir, sitedircase = makepath(sitedir)
                File "/opt/saltstack/salt/lib/python3.10/site.py", line 97, in makepath
                  dir = os.path.join(*paths)
                File "/opt/saltstack/salt/lib/python3.10/posixpath.py", line 76, in join
                  a = os.fspath(a)
              TypeError: expected str, bytes or os.PathLike object, not NoneType
              [end of output]

          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: subprocess-exited-with-error

        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> See above for output.

        note: This error originates from a subprocess, and is likely not a problem with pip.
    stdout:
        Collecting saltext.vmware
          Using cached saltext.vmware-23.4.4.0rc1-py2.py3-none-any.whl (396 kB)
        Requirement already satisfied: salt>=3005 in /opt/saltstack/salt/lib/python3.10/site-packages (from saltext.vmware) (3006.1)
        Collecting pyvmomi==7.0.3 (from saltext.vmware)
          Using cached pyvmomi-7.0.3.tar.gz (592 kB)
          Preparing metadata (setup.py): started
          Preparing metadata (setup.py): finished with status 'done'
        Collecting jinja2<=3.1.0 (from saltext.vmware)
          Using cached Jinja2-3.1.0-py3-none-any.whl (132 kB)
        Requirement already satisfied: requests>=2.3.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (2.25.1)
        Requirement already satisfied: six>=1.7.3 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (1.16.0)
        Requirement already satisfied: MarkupSafe>=2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from jinja2<=3.1.0->saltext.vmware) (2.1.2)
        Requirement already satisfied: certifi==2022.12.7 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2022.12.7)
        Requirement already satisfied: cffi==1.14.6 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.14.6)
        Requirement already satisfied: chardet==3.0.4 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.0.4)
        Requirement already satisfied: cheroot==8.5.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (8.5.2)
        Requirement already satisfied: cherrypy==18.6.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (18.6.1)
        Requirement already satisfied: contextvars==2.4 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.4)
        Requirement already satisfied: cryptography==39.0.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (39.0.2)
        Requirement already satisfied: distro==1.5.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.5.0)
        Requirement already satisfied: idna==2.8 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.8)
        Requirement already satisfied: immutables==0.15 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (0.15)
        Requirement already satisfied: importlib-metadata==6.0.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (6.0.0)
        Requirement already satisfied: jaraco.classes==3.2.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.2.1)
        Requirement already satisfied: jaraco.collections==3.4.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.4.0)
        Requirement already satisfied: jaraco.functools==2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.0)
        Requirement already satisfied: jaraco.text==3.5.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.5.1)
        INFO: pip is looking at multiple versions of salt to determine which version is compatible with other requirements. This could take a while.
        Collecting salt>=3005 (from saltext.vmware)
          Using cached salt-3006.0.tar.gz (20.4 MB)
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'error'
```

**Comment by peterbaumert** [comment]
reinstalled all of salt and works now.
