### ISSUE TITLE
Extension destroys Salt 3006.1 installation due to conflicting jinja requirements

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt-ext-modules-vmware#383]
Installing saltext.vmware on Salt 3006.1 causes pip to uninstall Salt due to conflicting jinja requirements:

```
mkdir vagrant-salt-ext-modules-vmware && cd vagrant-salt-ext-modules-vmware && vagrant init almalinux/9 && vagrant up && vagrant ssh

sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/3006.repo | sudo tee /etc/yum.repos.d/salt.repo

sudo dnf install -y salt-minion salt-cloud

$ sudo salt-pip -v install saltext.vmware
Using pip 22.3.1 from /opt/saltstack/salt/lib/python3.10/site-packages/pip (python 3.10)
Collecting saltext.vmware
  Downloading saltext.vmware-23.4.4.0rc1-py2.py3-none-any.whl (396 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 396.7/396.7 kB 17.0 MB/s eta 0:00:00
Collecting pyvmomi==7.0.3
  Downloading pyvmomi-7.0.3.tar.gz (592 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 592.3/592.3 kB 50.4 MB/s eta 0:00:00
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info
  writing /tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'sample'
  adding license file 'LICENSE.txt'
  adding license file 'NOTICE.txt'
  writing manifest file '/tmp/pip-pip-egg-info-i5b0z1xk/pyvmomi.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Collecting jinja2<=3.1.0
  Downloading Jinja2-3.1.0-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 51.8 MB/s eta 0:00:00
Requirement already satisfied: salt>=3005 in /opt/saltstack/salt/lib/python3.10/site-packages (from saltext.vmware) (3006.1)
Requirement already satisfied: requests>=2.3.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (2.25.1)
Requirement already satisfied: six>=1.7.3 in /opt/saltstack/salt/lib/python3.10/site-packages (from pyvmomi==7.0.3->saltext.vmware) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from jinja2<=3.1.0->saltext.vmware) (2.1.2)
Requirement already satisfied: pyzmq==23.2.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (23.2.0)
Requirement already satisfied: jaraco.collections==3.4.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.4.0)
Requirement already satisfied: cheroot==8.5.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (8.5.2)
Requirement already satisfied: jaraco.classes==3.2.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.2.1)
Requirement already satisfied: python-dateutil==2.8.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.8.1)
Requirement already satisfied: immutables==0.15 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (0.15)
Requirement already satisfied: importlib-metadata==6.0.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (6.0.0)
Requirement already satisfied: distro==1.5.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.5.0)
Requirement already satisfied: jaraco.text==3.5.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.5.1)
Requirement already satisfied: idna==2.8 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.8)
Collecting salt>=3005
  Downloading salt-3006.0.tar.gz (20.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 19.1 MB/s eta 0:00:00
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Downloading setuptools-67.8.0-py3-none-any.whl (1.1 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 23.3 MB/s eta 0:00:00
  Collecting wheel
    Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 25.0 MB/s eta 0:00:00
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-67.8.0 wheel-0.40.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

  [notice] A new release of pip available: 22.3.1 -> 23.1.2
  [notice] To update, run: /opt/saltstack/salt/bin/python3.10 -m pip install --upgrade pip
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  <string>:1265: UserWarning: Warning: distutils is deprecated and shall be removed in Python 3.12, advise migrate to using setuptools
  running egg_info
  writing salt.egg-info/PKG-INFO
  writing dependency_links to salt.egg-info/dependency_links.txt
  writing entry points to salt.egg-info/entry_points.txt
  writing requirements to salt.egg-info/requires.txt
  writing top-level names to salt.egg-info/top_level.txt
  reading manifest file 'salt.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  adding license file 'NOTICE'
  adding license file 'AUTHORS'
  writing manifest file 'salt.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  <string>:1265: UserWarning: Warning: distutils is deprecated and shall be removed in Python 3.12, advise migrate to using setuptools
  running dist_info
  creating /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info
  writing /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/entry_points.txt
  writing requirements to /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  adding license file 'NOTICE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/pip-modern-metadata-1mz7_6m5/salt.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-1mz7_6m5/salt-3006.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: looseversion in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.0.2)
Requirement already satisfied: PyYAML in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (5.4.1)
Requirement already satisfied: pycryptodomex>=3.9.8 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (3.9.8)
Requirement already satisfied: msgpack!=0.5.5,>=0.5 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (22.0)
Collecting pyzmq==25.0.2
  Downloading pyzmq-25.0.2-cp310-cp310-manylinux_2_28_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 78.0 MB/s eta 0:00:00
Requirement already satisfied: contextvars in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (2.4)
Requirement already satisfied: jmespath in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (1.0.1)
Requirement already satisfied: psutil>=5.0.0 in /opt/saltstack/salt/lib/python3.10/site-packages (from salt>=3005->saltext.vmware) (5.8.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.3.0->pyvmomi==7.0.3->saltext.vmware) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.3.0->pyvmomi==7.0.3->saltext.vmware) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /opt/saltstack/salt/lib/python3.10/site-packages (from requests>=2.3.0->pyvmomi==7.0.3->saltext.vmware) (2022.12.7)
Building wheels for collected packages: pyvmomi, salt
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pyVmomi
  copying pyVmomi/Cache.py -> build/lib/pyVmomi
  copying pyVmomi/Differ.py -> build/lib/pyVmomi
  copying pyVmomi/DynamicTypeManagerHelper.py -> build/lib/pyVmomi
  copying pyVmomi/Iso8601.py -> build/lib/pyVmomi
  copying pyVmomi/ManagedMethodExecutorHelper.py -> build/lib/pyVmomi
  copying pyVmomi/SoapAdapter.py -> build/lib/pyVmomi
  copying pyVmomi/StubAdapterAccessorImpl.py -> build/lib/pyVmomi
  copying pyVmomi/Version.py -> build/lib/pyVmomi
  copying pyVmomi/VmomiSupport.py -> build/lib/pyVmomi
  copying pyVmomi/__init__.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_core.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_eam.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_pbm.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_query.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_sms.py -> build/lib/pyVmomi
  copying pyVmomi/_typeinfo_vim.py -> build/lib/pyVmomi
  copying pyVmomi/pyVmomiSettings.py -> build/lib/pyVmomi
  creating build/lib/pyVim
  copying pyVim/__init__.py -> build/lib/pyVim
  copying pyVim/connect.py -> build/lib/pyVim
  copying pyVim/pyVmomiFssAdapter.py -> build/lib/pyVim
  copying pyVim/sso.py -> build/lib/pyVim
  copying pyVim/task.py -> build/lib/pyVim
  /opt/saltstack/salt/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/Cache.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/Differ.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/DynamicTypeManagerHelper.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/Iso8601.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/ManagedMethodExecutorHelper.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/SoapAdapter.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/StubAdapterAccessorImpl.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/Version.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/VmomiSupport.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/__init__.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_core.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_eam.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_pbm.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_query.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_sms.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/_typeinfo_vim.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  copying build/lib/pyVmomi/pyVmomiSettings.py -> build/bdist.linux-x86_64/wheel/pyVmomi
  creating build/bdist.linux-x86_64/wheel/pyVim
  copying build/lib/pyVim/__init__.py -> build/bdist.linux-x86_64/wheel/pyVim
  copying build/lib/pyVim/connect.py -> build/bdist.linux-x86_64/wheel/pyVim
  copying build/lib/pyVim/pyVmomiFssAdapter.py -> build/bdist.linux-x86_64/wheel/pyVim
  copying build/lib/pyVim/sso.py -> build/bdist.linux-x86_64/wheel/pyVim
  copying build/lib/pyVim/task.py -> build/bdist.linux-x86_64/wheel/pyVim
  running install_egg_info
  running egg_info
  writing pyvmomi.egg-info/PKG-INFO
  writing dependency_links to pyvmomi.egg-info/dependency_links.txt
  writing requirements to pyvmomi.egg-info/requires.txt
  writing top-level names to pyvmomi.egg-info/top_level.txt
  reading manifest file 'pyvmomi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'sample'
  adding license file 'LICENSE.txt'
  adding license file 'NOTICE.txt'
  writing manifest file 'pyvmomi.egg-info/SOURCES.txt'
  Copying pyvmomi.egg-info to build/bdist.linux-x86_64/wheel/pyvmomi-7.0.3-py3.10.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/pyvmomi-7.0.3.dist-info/WHEEL
  creating '/tmp/pip-wheel-kcpdys9r/pyvmomi-7.0.3-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'pyVim/__init__.py'
  adding 'pyVim/connect.py'
  adding 'pyVim/pyVmomiFssAdapter.py'
...
  adding 'salt-3006.0.dist-info/entry_points.txt'
  adding 'salt-3006.0.dist-info/top_level.txt'
  adding 'salt-3006.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for salt (pyproject.toml) ... done
  Created wheel for salt: filename=salt-3006.0-py3-none-any.whl size=9928200 sha256=87e76a8e99c5743263c6a2ea2b9d44065f1dedc0bcc1009cec94a34487b4b356
  Stored in directory: /root/.cache/pip/wheels/95/a0/6c/82beca06519dc82625530cd14e55b2a1f891addc5565ff46e8
Successfully built pyvmomi salt
Installing collected packages: pyzmq, jinja2, salt, pyvmomi, saltext.vmware
  Attempting uninstall: pyzmq
    Found existing installation: pyzmq 23.2.0
    Uninstalling pyzmq-23.2.0:
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/pyzmq-23.2.0.dist-info/
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/zmq/
      Successfully uninstalled pyzmq-23.2.0
  Do not adjust rpath of /tmp/pip-target-45kmlz__/pyzmq.libs/libsodium-f0c5df0c.so.23.3.0
  WARNING: Unable to find library libsodium-f0c5df0c.so.23.3.0 linked from /tmp/pip-target-45kmlz__/pyzmq.libs/libzmq-c2f9f1be.so.5.2.4
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/pyzmq.libs/libzmq-c2f9f1be.so.5.2.4
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/_device.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/_poll.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/_proxy_steerable.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/_version.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/context.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/error.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/message.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/socket.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/backend/cython/../../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/backend/cython/utils.cpython-310-x86_64-linux-gnu.so
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/devices/../../pyzmq.libs/libzmq-c2f9f1be.so.5.2.4 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /tmp/pip-target-45kmlz__/zmq/devices/../../pyzmq.libs/libsodium-f0c5df0c.so.23.3.0 is not in /opt/saltstack/salt
  WARNING: In `rpath_only mode` but /lib64/libstdc++.so.6 is not in /opt/saltstack/salt
  Do not adjust rpath of /tmp/pip-target-45kmlz__/zmq/devices/monitoredqueue.cpython-310-x86_64-linux-gnu.so
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.2
    Uninstalling Jinja2-3.1.2:
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/Jinja2-3.1.2.dist-info/
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/jinja2/
      Successfully uninstalled Jinja2-3.1.2
  Attempting uninstall: salt
    Found existing installation: salt 3006.1
    Uninstalling salt-3006.1:
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/salt-3006.1.dist-info/
      Removing file or directory /opt/saltstack/salt/lib/python3.10/site-packages/salt/
      Removing file or directory /opt/saltstack/salt/salt
      Removing file or directory /opt/saltstack/salt/salt-api
      Removing file or directory /opt/saltstack/salt/salt-call
      Removing file or directory /opt/saltstack/salt/salt-cloud
      Removing file or directory /opt/saltstack/salt/salt-cp
      Removing file or directory /opt/saltstack/salt/salt-key
      Removing file or directory /opt/saltstack/salt/salt-master
      Removing file or directory /opt/saltstack/salt/salt-minion
      Removing file or directory /opt/saltstack/salt/salt-pip
      Removing file or directory /opt/saltstack/salt/salt-proxy
      Removing file or directory /opt/saltstack/salt/salt-run
      Removing file or directory /opt/saltstack/salt/salt-ssh
      Removing file or directory /opt/saltstack/salt/salt-syndic
      Removing file or directory /opt/saltstack/salt/share/man/man1/
      Removing file or directory /opt/saltstack/salt/share/man/man7/
      Removing file or directory /opt/saltstack/salt/spm
      Successfully uninstalled salt-3006.1
  Creating /tmp/pip-target-45kmlz__/bin
  changing mode of /tmp/pip-target-45kmlz__/bin/salt to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-api to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-call to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-cloud to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-cp to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-key to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-master to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-minion to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-pip to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-proxy to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-run to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-ssh to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/salt-syndic to 755
  changing mode of /tmp/pip-target-45kmlz__/bin/spm to 755
Successfully installed jinja2-3.1.0 pyvmomi-7.0.3 pyzmq-25.0.2 salt-3006.0 saltext.vmware-23.4.4.0rc1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: /opt/saltstack/salt/bin/python3.10 -m pip install --upgrade pip
```

This is due to saltext.vmware requiring `Jinja2 <= 3.1.0`:

https://github.com/saltstack/salt-ext-modules-vmware/blob/e50073f4f298b0b5579a25ce4f070a36ef28c401/setup.cfg#L44

whereas Salt 3006.1 is bundled with `3.1.2`

**Comment by ggiesen** [comment]
Even once I fix that, on my production instance I get:

```
[ERROR   ] Error processing Salt Extension saltext.vmware(version: 23.4.4.0rc1): No module named 'saltext.vmware'
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1462, in catch_entry_points_exception
    yield context
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 155, in _module_dirs
    loaded_entry_point = entry_point.load()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/opt/saltstack/salt/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'saltext.vmware'
```

**Comment by joechainz** [comment]
Fixed https://github.com/saltstack/salt-ext-modules-vmware/pull/384

**Comment by dmurphy18** [comment]
@ggiesen Need to get a template here for this repo, but please use something similar to regular salt issue template and fill out versions-report or test.versions, so know what OS you are even using here.

**Comment by ggiesen** [comment]
After some further debugging, I don't think this is an issue with saltext.vmware, but rather a salt-pip bug, probably related to https://github.com/saltstack/salt/issues/64662. I'm going to close this issue and append it to that issue.
